### ISSUE TITLE
link for weights does not work

### ISSUE THREAD

**Issue by hnekoeiq** [fbraza/FruitDetect#7]
Hi @fbraza ,

Thanks for the great repo and detailed README. The current link for [weights](https://drive.google.com/file/d/1oxkA6hP24AuDrQCSPTprlKsDxRXWiFiW/view?usp=sharing) does not work. Could you update it with the correct link?

Thanks

**Comment by fbraza** [comment]
Hi @hnekoeiq,

Thank you for spotting it. Link has been updated.
Please star the repo if you find it useful.

All the best

Faouzi

**Comment by hnekoeiq** [comment]
Thanks for your prompt reply.
The link still is not working for me though. It says `No preview available`

**Comment by fbraza** [comment]
Hi @hnekoeiq,

I have the same. Look at the screenshot below. Spot the download sign / label in the upper right corner and click on this. 
You can download the weights from there.

![Screenshot from 2021-11-12 18-35-37](https://user-images.githubusercontent.com/43014610/141510357-8608c6de-f9b3-4441-8e93-962f47825d37.png)

**Comment by hnekoeiq** [comment]
Hi @fbraza,

Thanks again. But this is what I get ...
![Screenshot from 2021-11-12 12-45-25](https://user-images.githubusercontent.com/43013139/141511700-bfed5b21-f59a-4af8-b39b-10f188e7d7d2.png)

**Comment by fbraza** [comment]
Ok sorry for the inconvenience. I will use git LFS and solve this.

**Comment by fbraza** [comment]
Hi @hnekoeiq,

I added the weights to the repository. 
Now I guess you can get them from there or by cloning the repository.
Hope this will work for you ^_^ 

Best of luck

Faouzi

**Comment by fbraza** [comment]
Hello @hnekoeiq,

Let me know if you can download the weights.
If so, I can close the issue

Many thanks
